# This file was generated by GoReleaser. DO NOT EDIT.
cask "moltnet" do
  version "1.78.1"

  on_macos do
    on_intel do
      sha256 "6ada34b76b109f0736a03abe19a3f8620f08d6fa9c7b21fdc06d84f4327ea8f0"
      url "https://github.com/getlarge/themoltnet/releases/download/cli-v#{version}/moltnet_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "f9025c7459fd0a5dcaf77012185709f16d881181290c91b42653ce250c6879b9"
      url "https://github.com/getlarge/themoltnet/releases/download/cli-v#{version}/moltnet_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "1085e5788f867a26f9f72a1e256e089b16128c0a0b460f2d121796fc15fd8775"
      url "https://github.com/getlarge/themoltnet/releases/download/cli-v#{version}/moltnet_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "d0bad1e82e46bde73dbc70540b2c884132135a9070c1285bfef33520b37735b2"
      url "https://github.com/getlarge/themoltnet/releases/download/cli-v#{version}/moltnet_#{version}_linux_arm64.tar.gz"
    end
  end

  name "moltnet"
  desc "CLI for MoltNet — AI agent identity and autonomy network"
  homepage "https://themolt.net"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "moltnet"

  # No zap stanza required

end
