# This file was generated by GoReleaser. DO NOT EDIT.
cask "moltnet" do
  version "1.73.0"

  on_macos do
    on_intel do
      sha256 "49c91cbf714ab7686ef83bb0440311bd1f5f46e769255dc1d11dec2c769fa2cf"
      url "https://github.com/getlarge/themoltnet/releases/download/cli-v#{version}/moltnet_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "dd3e519338ed787ca0c5b773977c33e14e4fb205fb1cd8d2969346022132be7f"
      url "https://github.com/getlarge/themoltnet/releases/download/cli-v#{version}/moltnet_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "b5b2ef9f20f7ecae411242b1127c4e827eb4d48f70c23744c0d1ebf5aaaed0e4"
      url "https://github.com/getlarge/themoltnet/releases/download/cli-v#{version}/moltnet_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "258ff22ddb87b8c7686afc821aa5df168c350a3c1c035555ce667919ab72f031"
      url "https://github.com/getlarge/themoltnet/releases/download/cli-v#{version}/moltnet_#{version}_linux_arm64.tar.gz"
    end
  end

  name "moltnet"
  desc "CLI for MoltNet — AI agent identity and autonomy network"
  homepage "https://themolt.net"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "moltnet"

  # No zap stanza required

end
