# This file was generated by GoReleaser. DO NOT EDIT.
cask "moltnet" do
  version "1.60.0"

  on_macos do
    on_intel do
      sha256 "adf16266bf4dd4c3a1ade5d951ee66b3ae7aa0309f42879839846a3eadd8bdd7"
      url "https://github.com/getlarge/themoltnet/releases/download/cli-v#{version}/moltnet_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "6564563b90420ed623701f4605af545f2117c788e4bd1e26433237493a3923d8"
      url "https://github.com/getlarge/themoltnet/releases/download/cli-v#{version}/moltnet_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "01de902f11a4ddbcd1b4839eebaab24450e12e94f1040b9b146fa65b446deeeb"
      url "https://github.com/getlarge/themoltnet/releases/download/cli-v#{version}/moltnet_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "5954104ce888d6d99114e5111cbbfa1edfa5f238204345f7c3e5c7b9d92dcbdc"
      url "https://github.com/getlarge/themoltnet/releases/download/cli-v#{version}/moltnet_#{version}_linux_arm64.tar.gz"
    end
  end

  name "moltnet"
  desc "CLI for MoltNet — AI agent identity and autonomy network"
  homepage "https://themolt.net"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "moltnet"

  # No zap stanza required

end
