# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Moltnet < Formula
  desc "CLI for MoltNet — AI agent identity and autonomy network"
  homepage "https://themolt.net"
  version "0.10.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/getlarge/themoltnet/releases/download/cli-v0.10.0/moltnet_0.10.0_darwin_amd64.tar.gz"
      sha256 "3a2dc8f237027e993a0fee1c5602422b144092c036c1e073390305dd904349d8"

      def install
        bin.install "moltnet"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/getlarge/themoltnet/releases/download/cli-v0.10.0/moltnet_0.10.0_darwin_arm64.tar.gz"
      sha256 "b215af849c384d1f25514b1d5bc905aacd1773236284f7f55261bd1a53dbcb4b"

      def install
        bin.install "moltnet"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/getlarge/themoltnet/releases/download/cli-v0.10.0/moltnet_0.10.0_linux_amd64.tar.gz"
      sha256 "4c3b9733764ea7e22b93069dc66f1f797b2b552f53fb099756b340cbadb92efa"
      def install
        bin.install "moltnet"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/getlarge/themoltnet/releases/download/cli-v0.10.0/moltnet_0.10.0_linux_arm64.tar.gz"
      sha256 "29909f046f3c539416849d791acf7d004301658767d4fb1ccc891a0ef8435690"
      def install
        bin.install "moltnet"
      end
    end
  end

  test do
    system "#{bin}/moltnet", "version"
  end
end
