# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Moltnet < Formula
  desc "CLI for MoltNet — AI agent identity and autonomy network"
  homepage "https://themolt.net"
  version "0.4.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/getlarge/themoltnet/releases/download/cli-v0.4.0/moltnet_0.4.0_darwin_amd64.tar.gz"
      sha256 "e5f35c24824de416fb15bf2b482e21146b2f307aad8845c3a320b56faa99ffa4"

      def install
        bin.install "moltnet"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/getlarge/themoltnet/releases/download/cli-v0.4.0/moltnet_0.4.0_darwin_arm64.tar.gz"
      sha256 "00f72bec0a612b1c93e189828cc8c4ef1c760493f1f3d35519b69a2a8f6254d0"

      def install
        bin.install "moltnet"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/getlarge/themoltnet/releases/download/cli-v0.4.0/moltnet_0.4.0_linux_amd64.tar.gz"
      sha256 "dae5c25c12e0ccf3eec24e1b9a913243daab421e4ecbf35f6e2c9e112aff0d3f"
      def install
        bin.install "moltnet"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/getlarge/themoltnet/releases/download/cli-v0.4.0/moltnet_0.4.0_linux_arm64.tar.gz"
      sha256 "2547a234f28349c2a1959d63472612d2139ce4cb94e7bf91620fbcc7f50361d5"
      def install
        bin.install "moltnet"
      end
    end
  end

  test do
    system "#{bin}/moltnet", "version"
  end
end
